[package]
name = "memfs"
version.workspace = true
edition.workspace = true

[dependencies]
trace = { path = "../trace" }
storage = { path = "../storage" }
fuser.workspace = true
libc.workspace = true
tokio.workspace = true
uuid.workspace = true
